### PR TITLE
[terra-clinical-result] Fixed incorrect prop descriptions.

### LINKED ISSUE #764: [terra-clinical-result] Fix incorrect prop descriptions
# Bug Report

## Description

Some of the Clinical result prop descriptions were accidentally transposed and incorrect when first added and need to be updated:

1. **isUnverified**
https://github.com/cerner/terra-clinical/blob/1b889e41cbeba71743bd19210e94b0c1a70744f1/packages/terra-clinical-result/src/ClinicalResult.jsx#L29-L32
Correct to:
```
   /** 
    * Adds indicator if result value has not been verified, typically if it has not been 
    * authenticated and committed to the patient's chart.
    */ 
```

2. **isModified**
https://github.com/cerner/terra-clinical/blob/1b889e41cbeba71743bd19210e94b0c1a70744f1/packages/terra-clinical-result/src/ClinicalResult.jsx#L49-L52
Correct to:
```
   /** 
    * Add indicator if the result value has been modified to a different value from its 
    * previously documented value for the same clinical result date & time.
    */ 
```

3. **hasComment**
https://github.com/cerner/terra-clinical/blob/1b889e41cbeba71743bd19210e94b0c1a70744f1/packages/terra-clinical-result/src/ClinicalResult.jsx#L53-L56
Correct to:
```
   /** 
    * Add indicator if the result value has an additional comment applied to the clinical result value.
    */ 
```

## Notes
Tech only update, UX Review and Functional Review is not needed.

## @ Mentions

@mndrsn

### PR DESCRIPTION
**Pull request by saket2403**
### Summary

Closes #764 

### Deployment Link
https://terra-clinic-prop-desc-ptvevvb.herokuapp.com/components/terra-clinical-result/clinical-result/clinical-result

### Notes
Tech only change, no UX or Functional review needed.

### CODE REVIEW

File: packages/terra-clinical-result/src/ClinicalResult.jsx [hunk 1]
```diff
@@ -47,12 +48,13 @@ const propTypes = {
    */
   isTruncated: PropTypes.bool,
   /**
-   *  If the Result value has not been authenticated and committed to patient chart.
-   */
+    * Add indicator if the result value has been modified to a different value from its
```
Comment (tbiethman) [inline packages/terra-clinical-result/src/ClinicalResult.jsx:51]: Let's be consistent with the first change:

```suggestion
    * Adds indicator if the result value has been modified to a different value from its
```

File: packages/terra-clinical-result/src/ClinicalResult.jsx [hunk 2]
```diff
@@ -47,12 +48,13 @@ const propTypes = {
...
+    * previously documented value for the same clinical result date & time.
+    */
   isModified: PropTypes.bool,
   /**
-   *  If the Result value has been modified from it's original value for the same clinically documented event & datetime.
-   */
+    * Add indicator if the result value has an additional comment applied to the clinical result value.
```
Comment (tbiethman) [inline packages/terra-clinical-result/src/ClinicalResult.jsx:56]:
```suggestion
    * Adds indicator if the result value has an additional comment applied to the clinical result value.
```

**Review by tbiethman — APPROVED** [review]

**Review by ShettyAkarsh — APPROVED** [review]

**Review by benbcai — APPROVED** [review]
