### PR TITLE
[terra-clinical-result] Fixing entered in error issues with flowsheetcell

### LINKED ISSUE #634: [terra-clinical-result] Multiple Result Indicator shows interpretation coloration for in error results
# Bug Report

## Description

When sending multiple results with 'entered-in-error' to allow for full tally of total results, the interpretation of In Error values is included when determining coloration of the indicator.  These values were entered in error, and to our understanding, should not be considered clinically relevant to trigger coloration.

## Steps to Reproduce

1. Send multiple results, first being a result not entered in error.
2. Provide critical interpretation and status of 'entered-in-error' for one or more of the subsequent results.

## Additional Context / Screenshots

image

## Expected Behavior
Numeric total is honored and displayed accordingly.  Interpretation for values marked as entered in error is ignored when determining coloration.

## Possible Solution
Allow status to be considered during [createEndAdditionalResultsStack](https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx#L97).

## Environment

* Component Name and Version: terra-clinical-result 1.2.0 in FlowsheetResultCell 
* Browser Name and Version: Any
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): N/A

### LINKED ISSUE #635: [terra-clinical-result] In Error Blood Pressure Misalignment
# Bug Report

## Description
Providing a normalcy other than normal to an in error systolic result value for a blood pressure results in misalignment of the In Error text.

## Steps to Reproduce

1. Provide non-normal interpretation and status 'entered-in-error' for the systolic component of a Blood Pressure within the FlowsheetResultCell.

## Additional Context / Screenshots

image

## Expected Behavior
A blood pressure with a non-normal in error systolic result aligns with other result cell data.

## Environment

* Component Name and Version: terra-clinical-result 1.2.0 in FlowsheetResultCell 
* Browser Name and Version: Any
* Node/npm Version: N/A
* Webpack Version: N/A
* Operating System and version (desktop or mobile): N/A

### PR DESCRIPTION
**Pull request by BenBoersma**
### Summary
Fixes https://github.com/cerner/terra-clinical/issues/634
Added some checking to make sure interpretation was being considered in extra results in that specific result was entered in error.
Fixes https://github.com/cerner/terra-clinical/issues/635
Added some checking to make sure interpretation class wasn't added to primary display in the case of the result being entered in error. 
Added a new test to test for the above cases and similar ones.

Closes #634
Closes #635

### Deployment Link

https://terra-clinical-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx [hunk 1]
```diff
@@ -141,12 +141,8 @@ const createClinicalResultDisplay = (children, hasUnverifiedIcon, hasInterpretat
   return (<div key={(`ClinicalResultDisplay-${resultKeyID}`)} className={primaryResultClassnames} ref={containerDivRef}>{children}</div>);
 };
 
-const createStandardResultDisplay = (resultDataItem, hasUnverifiedIcon, hasInterpretationIcon, hideUnit, resultKeyID, numericOverflow, containerDivRef) => {
-  const {
-    status,
-  } = resultDataItem;
+const createStandardResultDisplay = (resultDataItem, isStatusInError, hasUnverifiedIcon, hasInterpretationIcon, hideUnit, resultKeyID, numericOverflow, containerDivRef) => {
```
Comment (yuderekyu) [inline packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx:144]: which one of these params are required and which ones are optional? taking a page out of matt's book, could we move towards an object param api for these functions?

Comment (BenBoersma) [reply packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx]: I think we might want to save bigger API changes in the cleanup PR that is eventually coming.  I've dropped it down to just passing in the attributes object for now. https://github.com/cerner/terra-clinical/pull/639/commits/2aa1cc5bf73202c44d9808132ec1015e621fa52c

Comment (yuderekyu) [reply packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx]: what is planned for the cleanup pr? do we need to create an issue that outlines these changes?

Comment (BenBoersma) [reply packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx]: Currently the cleanup PR is just going through the original release PR for clinical-result https://github.com/cerner/terra-clinical/pull/574 and addressing all the comments and issues on it that didn't get implemented along with going through the code to see if there are code blocks that could be clearer and easier to read. I don't think a tracking issue would hurt, since this isn't so much a bug as an internal enhancement.

**Comment by neilpfeiffer** [comment]
Reviewed: #639

Resolves: #634 and #635 
fixing when both interpretation and status were set to Entered-In-Error.



| UX +1 |
|---|

File: packages/terra-clinical-result/tests/jest/flowsheet-result-cell/FlowsheetResultCell.test.jsx [hunk 2]
```diff
@@ -140,6 +140,28 @@ describe('FlowsheetResultCell', () => {
...
+        },
+        diastolic: {
+          ...DefaultDiastolicResult,
+          status: 'entered-in-error',
+          interpretation: 'critical',
+        },
+      },
+      DefaultBloodPressureResult,
+    ];
+    const cell = shallowWithIntl(<FlowsheetResultCell resultDataSet={results} hideUnit />).dive();
```
Comment (emilyrohrbough) [inline packages/terra-clinical-result/tests/jest/flowsheet-result-cell/FlowsheetResultCell.test.jsx:161]: Is this the same test as above? Is there a way to validate the multiple result stack icon without interpretation?

Comment (BenBoersma) [reply packages/terra-clinical-result/tests/jest/flowsheet-result-cell/FlowsheetResultCell.test.jsx:161]: So this test is specifically testing one of the issues we were dealing with, where the multiple result stack icon would get its interpretation color based on an `entered in error` value which shouldn't happen. This test should render a default result in the flow sheet cell and with a multiple icon set that doesn't get the class to render it as `critical` since it is `entered-in-error`

The test above is a test to make sure the both the systolic value and diastolic value render the `enterered-in-error` changes.

Comment (emilyrohrbough) [reply packages/terra-clinical-result/tests/jest/flowsheet-result-cell/FlowsheetResultCell.test.jsx:161]: Should we add a simple assertion check to validate the `critical` classname has not been applied on the icon?

Comment (BenBoersma) [reply packages/terra-clinical-result/tests/jest/flowsheet-result-cell/FlowsheetResultCell.test.jsx:161]: Updated the test and test name, https://github.com/cerner/terra-clinical/pull/639/commits/111cb724c4d4c4db05e06c6aa19c7006cf69ccbc

**Comment by PaulSolDev** [comment]
Functional review complete. No issues identified.
