### PR TITLE
Clinical item view right align text plus clinical item display icon alignment

### LINKED ISSUE #463: [terra-clinical-item-view] Wrapping right aligned displays are no longer right aligned when they are wrapped
# Bug Report

## Description

Wrapping right aligned displays are no longer right aligned when they are wrapped.

This could potentially be fixed with a text-align of end within the 2 column layout on the even item (https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-item-view/src/ItemView.scss#L90-L97).

### PR DESCRIPTION
**Pull request by neilpfeiffer**
### Summary
Resolves #463 Wrapping right aligned displays are no longer right aligned when they are wrapped

### Additional Details
Adds a new prop to Clinical-Item-Display for `iconAlignment` - which should provide a passive update to anyone already using icons in Clinical-Item-Display, but provides the ability for consumers to set icons to `inline` for when Clinical-Item-View needs to be right aligned, resolving the flex icon spacing/positioning problem.

Also adds missing `primary` text style which is defaulted but wasn't an explicit option.

\\

Credit: Much of this comes from work done by @ShettyAkarsh in [his branch](https://github.com/cerner/terra-clinical/tree/ClinicalItemView-RightAlignWrappedText-issue).

----

### Functional Review

* New `iconAlignment` prop (one of `center`,`top`,`inline`) added to Clinical-Item-Display:  https://terra-clinical-deployed-pr-490.herokuapp.com/#/components/terra-clinical-item-display/clinical-item-display/clinical-item-display
* `iconAlignment="inline"` applied to Clinical-Item-View to fix icon+wrapping in right aligned displays: 
https://terra-clinical-deployed-pr-490.herokuapp.com/#/components/terra-clinical-item-view/clinical-item-view/clinical-item-view

### CODE REVIEW

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx [hunk 1]
```diff
@@ -51,11 +60,13 @@ const ItemDisplay = ({
   isTruncated,
   isDisabled,
   icon,
+  iconAlignment,
   ...customProps
 }) => {
   const componentClassNames = cx([
     'item-display',
     { 'is-disabled': isDisabled },
+    { [`icon-${iconAlignment}`]: iconAlignment && icon },
```
Comment (nramamurth) [inline packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Since `iconAlignment` defaults to `center` (truthy) if not provided, ```[`icon-${iconAlignment}`]: icon``` should suffice.

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx [hunk 2]
```diff
@@ -66,7 +77,10 @@ const ItemDisplay = ({
 
   let displayIcon;
   if (icon) {
-    displayIcon = <div className={cx('inline-icon')}>{icon}</div>;
+    const iconClassNames = cx([
+      'icon',
+    ]);
+    displayIcon = <div className={iconClassNames}>{icon}</div>;
```
Comment (mjhenkes) [inline packages/terra-clinical-item-display/src/ItemDisplay.jsx]: nit
```suggestion
    displayIcon = <div className={cx('icon')}>{icon}</div>;
```

**Comment by nramamurth** [comment]
Please remove the .DS_Store files. 

- packages/terra-clinical-item-view/tests/wdio/.DS_Store
- packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/.DS_Store

**Comment by nramamurth** [comment]
Is this an intended change for the icon that is themed? 

https://github.com/cerner/terra-clinical/pull/490/files#diff-14

File: packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/IconItemDisplay.test.jsx [hunk 3]
```diff
@@ -3,4 +3,14 @@ import IconSuccess from 'terra-icon/lib/icon/IconSuccess';
...
-export default () => <ItemDisplay text="Test Text" icon={<IconSuccess />} id="ItemDisplay" />;
+const testText = 'Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text Test Text';
+
+export default () => (
+  <React.Fragment>
+    <ItemDisplay text={`Center / default - ${testText}`} icon={<IconSuccess />} id="test-icon-center" />
+    <br />
+    <ItemDisplay text={`Top - ${testText}`} icon={<IconSuccess />} id="test-icon-top" iconAlignment="top" />
+    <br />
+    <ItemDisplay text={`Inline - ${testText}`} icon={<IconSuccess />} id="test-icon-inline" iconAlignment="inline" />
```
Comment (mjhenkes) [inline packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/IconItemDisplay.test.jsx]: I think the second line wrap of this item is getting cut off in the screenshots below.

**Comment by mjhenkes** [comment]
It seems like there are more screenshot changes than are necessary? I think we could trim down the # of files changed.

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 1 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Considered that, definitely is truthy - didn't know whether to be more explicit/protectionist, or to be more liberal.

**Comment by neilpfeiffer** [comment]
+1 with the # screenshot changes - will take a second pass and only dump/replace those being changed.

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 1 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Applied https://github.com/cerner/terra-clinical/pull/490/commits/64a30bf5d3762a293a49c28184defc2bfc287654

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 2 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Applied https://github.com/cerner/terra-clinical/pull/490/commits/64a30bf5d3762a293a49c28184defc2bfc287654

**Comment by neilpfeiffer** [comment]
> Please remove the .DS_Store files.
> 
> * packages/terra-clinical-item-view/tests/wdio/.DS_Store
> * packages/terra-clinical-onset-picker/tests/wdio/**snapshots**/.DS_Store

Removed https://github.com/cerner/terra-clinical/pull/490/commits/64a30bf5d3762a293a49c28184defc2bfc287654

File: packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/IconItemDisplay.test.jsx (hunk 3 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/IconItemDisplay.test.jsx]: Good call - inline block needed to be bound in block element to correctly capture edges of screeenshot. Fixed with https://github.com/cerner/terra-clinical/pull/490/commits/720eeeba8d785252384733168dcdb59c0a554097#diff-015ab00051023df5defba34800b2a700

**Comment by neilpfeiffer** [comment]
All comments have been applied and errors resolved. 


\
\
@nramamurth - I wasn't sure what you meant by your comment here? Did you have a line number?
> Is this an intended change for the icon that is themed?
> 
> https://github.com/cerner/terra-clinical/pull/490/files#diff-14

**Comment by nramamurth** [comment]
@neilpfeiffer My bad, link was incorrect. I was wondering about the update to the screenshot here: https://github.com/cerner/terra-clinical/pull/490/files#diff-c1ede1eb12546c3851c913763fb2ae61

**Comment by neilpfeiffer** [comment]
Thanks @nramamurth -- good catch -- comparing it to [previous](https://engineering.cerner.com/terra-clinical/#/evidence/terra-clinical-item-display/terra-clinical-item-display/en/terra-clinical-item-display/en/disabled-themed) to see why it would have changed to not color the icon.

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx [hunk 4]
```diff
@@ -35,14 +37,21 @@ const propTypes = {
...
+   * noticeable when the text display wraps multiple line.
+   * One of `'center'`, `'top'`, `'inline'`.
+   */
+  iconAlignment: PropTypes.oneOf(['center', 'top', 'inline']),
 };
 
 const defaultProps = {
   text: '',
-  textStyle: undefined,
+  textStyle: 'primary',
```
Comment (emilyrohrbough) [inline packages/terra-clinical-item-display/src/ItemDisplay.jsx]: By changing this default value this will be non-passive. Is that intended?

File: packages/terra-clinical-item-display/CHANGELOG.md [hunk 5]
```diff
@@ -3,6 +3,8 @@ ChangeLog
 
 Unreleased
 ----------
+### Changed
+* Added new prop for icon alignment and missing default primary text style
```
Comment (emilyrohrbough) [inline packages/terra-clinical-item-display/CHANGELOG.md]: Lets break this into two bullets

```
### Added
- iconAlignment prop

### Fixed 
- Added missing primary text style

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx [hunk 6]
```diff
@@ -51,11 +60,13 @@ const ItemDisplay = ({
   isTruncated,
   isDisabled,
   icon,
+  iconAlignment,
   ...customProps
 }) => {
   const componentClassNames = cx([
     'item-display',
     { 'is-disabled': isDisabled },
+    { [`icon-${iconAlignment}`]: iconAlignment },
```
Comment (nramamurth) [inline packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Should we even add this if there is no `icon`?

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 4 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: It actually should still passive since the color remains the same and primary was already assumed as the default, but you could never explicitly set it or test for it, or re-theme it.

**Comment by neilpfeiffer** [comment]
> Thanks @nramamurth -- good catch -- comparing it to [previous](https://engineering.cerner.com/terra-clinical/#/evidence/terra-clinical-item-display/terra-clinical-item-display/en/terra-clinical-item-display/en/disabled-themed) to see why it would have changed to not color the icon.

Found the issue and fixed here: https://github.com/cerner/terra-clinical/pull/490/commits/e5d7e8e274df8320107eaf0138c08110359e525f

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 4 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Fixed: https://github.com/cerner/terra-clinical/pull/490/commits/c86aab122395aef6137dbf691f69476d0949ab57#diff-7a7f3d6691e06f96790e846013f347ff

File: packages/terra-clinical-item-display/CHANGELOG.md (hunk 5 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/CHANGELOG.md]: Fixed: https://github.com/cerner/terra-clinical/pull/490/commits/c86aab122395aef6137dbf691f69476d0949ab57#diff-589055d761929f3cff8e25e6d51ef5b5

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx (hunk 6 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Thanks @naveen, was thinking about it backwards and removed `icon` instead of `iconAlignment`. Fixed: https://github.com/cerner/terra-clinical/pull/490/commits/c86aab122395aef6137dbf691f69476d0949ab57#diff-7a7f3d6691e06f96790e846013f347ff

File: packages/terra-clinical-item-display/docs/UpgradeGuide.md [hunk 7]
```diff
@@ -18,3 +18,4 @@
 * --terra-clinical-item-display-strong-color
 * --terra-clinical-item-display-strong-font-weight
 * --terra-clinical-item-display-strike-through-color
+* --terra-clinical-item-display-primary-color
```
Comment (emilyrohrbough) [inline packages/terra-clinical-item-display/docs/UpgradeGuide.md]: Should we include this new themeable var in the changelog as well? If I already pulled this version in, I wouldn't be looking here to cross check the available vars

File: packages/terra-clinical-item-display/src/ItemDisplay.jsx [hunk 8]
```diff
@@ -35,14 +37,22 @@ const propTypes = {
...
+   * The position of the icon to be displayed next to the text,
+   * noticeable when the text display wraps multiple line.
+   * One of `'center'`, `'top'`, `'inline'`.
+   */
+  iconAlignment: PropTypes.oneOf(['center', 'top', 'inline']),
 };
 
 const defaultProps = {
   text: '',
+  // TODO: textStyle should be set to 'primary' on the next major version bump
```
Comment (emilyrohrbough) [inline packages/terra-clinical-item-display/src/ItemDisplay.jsx]: Can we log an issue for this enhancement and add a reference here

File: packages/terra-clinical-item-view/src/ItemView.scss [hunk 9]
```diff
@@ -94,6 +94,7 @@
       // prematurely squished and maximize the available space for all labels.
       max-width: 60%;
       padding-left: 5px;
+      text-align: end;
```
Comment (emilyrohrbough) [inline packages/terra-clinical-item-view/src/ItemView.scss]: If `iconAlignment="inline" ` is not used, will this correctly right align? Or are the updated to add `iconAlignment="inline" ` for visuals on the doc site?

**Comment by neilpfeiffer** [comment]
Testing on IE revealed incorrect wrapping. Additional testing and fixes in progress.

File: packages/terra-clinical-item-view/src/ItemView.scss (hunk 9 above)
Comment (neilpfeiffer) [reply packages/terra-clinical-item-view/src/ItemView.scss]: Yes, the additional prop would be encouraged to be used (if not, the icon won't flow inline and will hang out to the left). 
+1 on updating the docsite example to include it or add a new one to especially call it out. Updated tests but would be good to have it documented as instructions.

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.

**Comment by neilpfeiffer** [comment]
+1

**Reviewed:**
- Solves for right aligned displays are no longer right aligned when they are wrapped

\
\
Verified by @neilpfeiffer, Ready for Release.

**Pass** |
-----------|
UX Review|
