### PR TITLE
Label Value View- Wrap Long Word If Provided

### LINKED ISSUE #220: Label Value View doesn't wrap the word
# Issue Description

Terra Clinical LabelValue View doesn't wrap the word. If a long word is provided as a text to LabelValueView, it will add the vertical scrollbar on the page instead of wrapping the word.

Need a way to wrap the long word.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

If the word is not fit on the screen, it should wrap the word on next line.

## Current Behavior
Word doesn't wrap, adds a horizontal scroll.

## Steps to Reproduce

To reproduce, render LabelValueView by providing textValue with a word with characters which doesn't fit in the available screen size.

## Environment

* Component Version: 1.3.0
* Browser Name and Version: Chrome v61.0.3163.100
* Operating System and version (desktop or mobile): Desktop OS X El Capitan v10.11.6

### PR DESCRIPTION
**Pull request by emilyrohrbough**
### Summary
Closes #220

### CODE REVIEW

File: packages/terra-clinical-label-value-view/tests/nightwatch/TextValueLabelValueView.jsx [hunk 1]
```diff
@@ -2,4 +2,15 @@ import React from 'react';
...
 import LabelValueView from '../../lib/LabelValueView';
 
-export default () => <LabelValueView id="LabelValueView" label="Label" textValue="Sample Text" />;
+const examples = () => (
+  <div>
+    <h3>Default Example:</h3>
+    <LabelValueView id="LabelValueView" label="Label" textValue="Sample Text" />
+    <h3>Applied max-width of 350px to show word wrapping:</h3>
+    <div style={{ maxWidth: '350px' }}>
+      <LabelValueView id="LongLabelValueView" label="A.really.long.label.value.view.sample.text.to.see.it.wrap.correctly." textValue="A.really.long.label.value.view.sample.text.to.see.it.wrap.correctly." />
```
Comment (StephenEsser) [inline packages/terra-clinical-label-value-view/tests/nightwatch/TextValueLabelValueView.jsx]: It's not often you get an opportunity to use `supercalifragilisticexpialidocious`

**Comment by PaulSolDev** [comment]
Functional review complete.  No issues identified.
